# Part 5
Let's recap :)

In [1]:
import numpy as np

In [3]:
# lets define simple numpy array
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

## Why numpy rathar than python?
Numpy package provides state-of-the-art mathmatcial methods so as to be developed in statistics, linear algebra and many other things. In comparison with python, it is really fast, and somehow handle the python's slow pace when it comes to heavy parallel calculations  

# How to create an array from existing data

### numpy.asarray

This appraoch is used to create an array by using the existing data in the form of lists, or tuples. This routine is useful in the scenario where we need to convert a python sequence into the numpy array object.

The syntax to use the asarray() routine is given below.

```numpy.asarray(sequence,  dtype = None, order = None)  ```

It accepts the following parameters.

1) sequence: It is the python sequence which is to be converted into the python array.

2)dtype: It is the data type of each item of the array.

3)order: It can be set to C or F. The default is 

In [15]:
import numpy as np  

l = [1, 2, 3, 4, 5, 6, 7]  
a = np.asarray(l);  
print(type(a))  
print(a) 

#------------------------------------

l1 = [[1, 2, 3, 4, 5, 6, 7],[8, 9]]  
a1 = np.asarray(l1);  
print(type(a1))  
print(a)  

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  # This is added back by InteractiveShellApp.init_path()


### numpy.frombuffer
This function is used to create an array by using the specified buffer. The syntax to use this buffer is given below.

```numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)```  
It accepts the following parameters.

- buffer: It represents an object that exposes a buffer interface.
- dtype: It represents the data type of the returned data type array. The default value is 0.
- count: It represents the length of the returned ndarray. The default value is -1.
- offset: It represents the starting position to read from. The default value is 0.

In [6]:
l = b'hello world'  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a)) 

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


### numpy.fromiter
This routine is used to create a ndarray by using an iterable object. It returns a one-dimensional ndarray object.

The syntax is given below.

```numpy.fromiter(iterable, dtype, count = - 1)  ```

It accepts the following parameters.

- Iterable: It represents an iterable object.
- dtype: It represents the data type of the resultant array items.
- count: It represents the number of items to read from the buffer in the array.

In [7]:
list = [0, 2, 4, 6]  
it = iter(list)  
x = np.fromiter(it, dtype = float)  
print(x)  
print(type(x))  

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


## Let's make a new numpy array from existing array :)

These methods ```np.vstack(), np.hstack(), np.hsplit(), .view(), copy()``` will be covered in this part.

let's define an array as below.

In [10]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
# the index that you wanna slice your array should be defined
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [11]:
# let's define two other numpy array
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

These two arrays can comforatably be stacked by these methods.

- ```np.vstack()``` : You can stack them vertically with vstack

- ```np.hstack() ``` : Or stack them horizontally with hstack

In [13]:
np.vstack((a1, a2)) # vertical stack

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [14]:
np.hstack((a1, a2)) # horizontal stack|

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using ```hsplit()```

! Recap : ```np.arrange(n)``` : for making ordered array from 1 to n-1

   Tip 2: ```np.reshape(x, y)``` : to convert the matirx to x * y matrix


In [17]:
x = np.arange(1, 25).reshape(2, 12)
'''
to split this array into three equally shaped arrays,
'''
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you wanted to split your array after the third and fourth column, you’d run:

In [18]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]), array([[ 4],
        [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

You can use the ```view()``` method to create a new array object that looks at the same data as the original array (a shallow copy).

Let's define an array

In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Now we create an array b1 by slicing a and modify the first element of b1. This will modify the corresponding element in a as well!

In [21]:
b1 = a[0, :]
print(b1)
b1[0] = 99
print(b1)
print(a)

[99  2  3  4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Using the copy method will make a complete ```copy()``` of the array and its data (a deep copy).

In [23]:
b2 = a.copy()
print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Basic array operations
Although there are a bunch of mathmatical operations in Numpy, in this part, we only cover addition, subtraction, multiplication, division, and so on.

In [31]:
'''
Addition
'''
data = np.array([1, 2, 5, 3])
ones = np.ones(4, dtype=int)
data + ones

array([2, 3, 6, 4])

In [32]:
'''
Subtraction
'''
data - ones

array([0, 1, 4, 2])

In [33]:
'''
Multiplication,
'''
data * ones

array([1, 2, 5, 3])

In [34]:
'''
Division
'''
data / ones

array([1., 2., 5., 3.])

If you want to find the sum of the elements in an array, you’d use ```sum()```.
It can also be defined as Integral in complex machine learning projects.

In [37]:
a = np.array([[1, 1],
               [2, 2]])
a.sum() # summation of all elements

6

In [38]:
a.sum(axis=0) # sum over the axis of rows 

array([3, 3])

In [39]:
a.sum(axis=1) # sum over the axis of colums

array([2, 4])

## Broadcasting
When do you wanna carry out calculations between **Scalar and Vector**, it can be used so as to enhance the pace and comfort of the mathmatical calculations. Numpy knows them and apply them to all rows and colums. The syntax is cake :)

In [41]:
data = np.array([3.0, 2.0])
data ** 2.0

array([9., 4.])

## More useful array operations
There are also numerous methods which are beyond the scope of this course; however, take a look to some methods, such as ``` np.mean(), np.std(), np.max(), np.min, np.tanh() ``` and so on throgh googling :)

## Acknowledgement:
Thanks for your stata-of-the-art documents
- [Numpy](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [Javatpoint](https://www.javatpoint.com/numpy-array-from-existing-data)