<a href="https://colab.research.google.com/github/salarMokhtariL/ML_Course/blob/main/0001_Prerequisites_NumPy/NumPy(P1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

# How to create a basic array


To create a NumPy array, you can use the function ```np.array()```.

All you need to do to create a simple array is pass a list to it. if you choose to,you can also specify the type of data in your list.





In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

Besides creating an array from a sequence of elements, you can easily create an array filled with 0's:

In [ ]:
np.zeros(2)

array([0., 0.])

Or an array filled with 1's:

In [ ]:
np.ones(2)

array([1., 1.])

Or even an empty array! The function `empty` creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [ ]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

You can create an array with a anage of elements:

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the **first number , last number**, and the **step size**

In [ ]:
np.arange(2,9,2)

array([2, 4, 6, 8])

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval:

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Specifying your data type 

While the default data type is floating point (`np.float64`), you can explicitly specify which data type want to using the `dtype` keywords.

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])