<a href="https://colab.research.google.com/github/salarMokhtariL/ML_Course/blob/main/0001_Prerequisites_NumPy/NumPy(P4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to convert a 1D array into a 2D array 
## (How to add a new axis to an array)




```
np.newaxis 
np.expand_dims
```






You can use `np.newaxis`  and   `np.expand` to increase the dimension of your existing array.
 
Using `np.newaxis` will increase the dimensions of your array by one dimension when used once.This means that a **1D** array will become a **2D** array, a **2D** array will become a **3D** array, and so on

**Examples**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

You can use `np.newaxis` to add a new axis :

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a2

array([[1, 2, 3, 4, 5, 6]])

You can explicitly convert a 1D array with either a row vector or using `np.newaxis` For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension :

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

Or, for column vector, you can insert an axis along the second dimension

In [ ]:
col_vector = a [:, np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by insterting a new axis at a specified position with `np.epand_dims`.


Example :


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

You can use `np.expand_dims` to add an axis at index postion 1 with :

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

You can use `np.expand_dims` to add an axis at index position 0 with :

In [ ]:
b = np.expand_dims(a, axis=0)
b.shape

(1, 6)

# Indexing and slicing


You can index and slicing NumPy array in the same ways you can slice Python lists.

In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data [1]

2

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you'll need to subset, slice, and/or index your arrays.

if you want to select values from your array that fulfill certain conditions, it's straightforward with NumPy.

Examples

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5 :

In [ ]:
print(a[a < 5])

[1 2 3 4]


You can also select, for examples, number that are equal to or greater than 5 , and use that condition to index an array

In [ ]:
five_up = (a >= 5)

print(a[five_up])

[ 5  6  7  8  9 10 11 12]


You can select elments that divisible by 2

In [ ]:
div_by_2 = a[a%2 == 0]
print(div_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the `&` and `|` operators :

In [ ]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

You can also make use of the logical operations **&** and **|** in order to return boolean values the specify whether or not the values in an array fulfill a ceartin condation.

this can be useful with arrays that contain names or other categorical values.

In [ ]:
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

---

---


You can also use `np.nonzero()` to select elements or indices from an array. 


Example )) print the indices of elements that are, Less than 5 

In [ ]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In this example,  a tuple of array was returend : one for each dimension. The first array represents the row indices where these values are found, and the seceond array represents the colum indices where the values found.

If you wan to generate a list of coordinates where the elements exist, you can zip the array, iterate the list of coordinates, and print them.  Exampel

In [ ]:
list_of_coordinates = list(zip(b[1], b[0]))

In [ ]:
for coord in list_of_coordinates:
  print(coord)

(0, 0)
(1, 0)
(2, 0)
(3, 0)


You can also use `np.nonzero()` to print the elements in an array that are less than 5 with :

In [ ]:
print(a[b])

[1 2 3 4]


If the elements you're looking for doesn't exist in the array, then the returned array of indices will be empty.  Example

In [ ]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


___
___
___
# numpy.nonzero

      numpy.nonzero(a)

Return the indices of the elements that are non-zero.


Returns a tuple of arrays, one for each dimension of a, containing the indices of the non-zero elements in that dimension. The values in a are always tested and returned in row-major, C-style order.

To group the indices by element, rather than dimension, use argwhere, which returns a row for each non-zero element.

  Parameters : a : *array_like*

  Input array.

Returns :tuple_of_arrays : *tuple*

Indices of elements that are non-zero.

In [ ]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [ ]:
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [ ]:
x[np.nonzero(x)]

array([3, 4, 5, 6])

In [ ]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]])

A common use for nonzero is to find the indices of an array, where a condition is True. Given an array a, the condition a > 3 is a boolean array and since False is interpreted as 0, np.nonzero(a > 3) yields the indices of the a where the condition is true.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.nonzero(a > 3)

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [ ]:
# Using this result to index a is equivalent to using the mask directly:
a[np.nonzero(a > 3)]

array([4, 5, 6, 7, 8, 9])

In [ ]:
a[a > 3]  # prefer this spelling

array([4, 5, 6, 7, 8, 9])

In [ ]:
# nonzero can also be called as a method of the array.

(a > 3).nonzero()


(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))