# Python Matrices and NumPy Arrays
A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. For example:

$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

This matrix is a 3x3 matrix because it has 3 rows and 3 columns.

## Python Matrix
Python doesn't have a built-in type for matrices. However, we can treat a list of a list as a matrix. For example:

In [1]:
A = [[1, 4, 5], 
    [-5, 8, 9]]

We can treat this list of a list as a matrix having 2 rows and 3 columns.

$$\begin{bmatrix} 1 & 4 & 5 \\ -5 & 8 & 9 \end{bmatrix}$$

In [2]:
A

[[1, 4, 5], [-5, 8, 9]]

Let's see how to work with a nested list.

In [3]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

column = [];        # empty list
for row in A:
  column.append(row[2])   

print("3rd column =", column)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12
3rd column = [5, 9, 11]


## NumPy Array
NumPy is a package for scientific computing which has support for a powerful N-dimensional array object. Before you can use NumPy

NumPy provides multidimensional array of numbers (which is actually an object). Let's take an example:

In [4]:
import numpy as np
a = np.array([1, 2, 3])
print(a)               # Output: [1, 2, 3]
print(type(a))         # Output: <class 'numpy.ndarray'>

[1 2 3]
<class 'numpy.ndarray'>


# NumPy Matrix

`class numpy.matrix(data, dtype = None, copy = True)`


Returns a matrix from an array-like object, or from a string of data. A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).

**Parameters**

data : *array_like or string*

If data is a string, it is interpreted as a matrix with commas or spaces separating columns, and semicolons separating rows.

dtype : *data-type*

Data-type of the output matrix.

copy : *bool* 

If data is already an ndarray, then this flag determines whether the data is copied (the default), or whether a view is constructed.

In [5]:
a = np.matrix('1 2; 3 4')

In [6]:
a

matrix([[1, 2],
        [3, 4]])

In [7]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])